apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml

images:
  - name: lscr.io/linuxserver/qbittorrent
    newName: lscr.io/linuxserver/qbittorrent
    newTag: latest
